/*
 * This is an auto-generated file - DO NOT EDIT! 
 * This is a C file generated by RCI Generator tool.
 * This file was generated on: 2015/02/03 10:59:49 
 * The command line arguments were: "hbujanda2:***** "Linux Application" 1.0.0.0-vendor=0x0300009F -noBackup -usenames=all -ccapiStub -rci_parser  config.rci"
 * The version of RCI Generator tool was: 2.0.0.0 */

#include  <stdio.h>
#include  "ccapi/ccapi.h"
#include  "ccapi_rci_functions.h"

#define XML_REQUEST_FILE_NAME "request.xml"

/* TODO: Move to user_context */
FILE * fp = NULL;

ccapi_global_error_id_t rci_session_start_cb(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_global_error_id_t rci_session_end_cb(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_global_error_id_t rci_action_start_cb(ccapi_rci_info_t * const info)
{
    ccapi_global_error_id_t error_id = CCAPI_GLOBAL_ERROR_NONE;

    UNUSED_PARAMETER(info);

    printf("    Called '%s'\n", __FUNCTION__);

    fp = fopen(XML_REQUEST_FILE_NAME, "wb+");
    if (fp == NULL)
    {
        printf("%s: Unable to create %s file\n", __FUNCTION__,  XML_REQUEST_FILE_NAME);
        error_id = CCAPI_GLOBAL_ERROR_XML_REQUEST_FAIL;
    }

    switch(info->action)
    {
        case CCAPI_RCI_ACTION_SET:
        {
            fprintf(fp, "<set_setting>");

            break;
        }
        case CCAPI_RCI_ACTION_QUERY:
        {
            fprintf(fp, "<query_setting>");

            break;
        }
#if (defined RCI_LEGACY_COMMANDS)
        case CCAPI_RCI_ACTION_DO_COMMAND:
        case CCAPI_RCI_ACTION_REBOOT:
        case CCAPI_RCI_ACTION_SET_FACTORY_DEFAULTS:
        {
            fprintf(fp, "TODO");

            break;
        }
#endif
    }

    return error_id;
}

ccapi_global_error_id_t rci_action_end_cb(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);

    printf("    Called '%s'\n", __FUNCTION__);

    if (fp != NULL)
        fclose(fp);

    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_serial_error_id_t rci_setting_serial_start(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_serial_error_id_t rci_setting_serial_end(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_serial_error_id_t rci_setting_serial_baud_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "2400";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_serial_error_id_t rci_setting_serial_baud_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_serial_error_id_t rci_setting_serial_parity_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "none";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_serial_error_id_t rci_setting_serial_parity_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_serial_error_id_t rci_setting_serial_databits_get(ccapi_rci_info_t * const info, uint32_t * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = 5;
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_serial_error_id_t rci_setting_serial_databits_set(ccapi_rci_info_t * const info, uint32_t const *const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_serial_error_id_t rci_setting_serial_xbreak_get(ccapi_rci_info_t * const info, ccapi_on_off_t * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = CCAPI_ON;
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_serial_error_id_t rci_setting_serial_xbreak_set(ccapi_rci_info_t * const info, ccapi_on_off_t const *const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_serial_error_id_t rci_setting_serial_txbytes_get(ccapi_rci_info_t * const info, uint32_t * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = 123;
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_start(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_end(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_ip_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "192.168.1.1";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_ip_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_subnet_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "192.168.1.1";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_subnet_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_gateway_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "192.168.1.1";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_gateway_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_dhcp_get(ccapi_rci_info_t * const info, ccapi_bool_t * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = CCAPI_TRUE;
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_dhcp_set(ccapi_rci_info_t * const info, ccapi_bool_t const *const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_dns_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "192.168.1.1";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_dns_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_mac_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "00:04:9D:AB:CD:EF";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_mac_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_duplex_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "auto";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_ethernet_error_id_t rci_setting_ethernet_duplex_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_time_error_id_t rci_setting_device_time_start(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_time_error_id_t rci_setting_device_time_end(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_time_error_id_t rci_setting_device_time_curtime_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "2002-05-30T09:30:10-0600";;
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_time_error_id_t rci_setting_device_time_curtime_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_info_error_id_t rci_setting_device_info_start(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_info_error_id_t rci_setting_device_info_end(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_info_error_id_t rci_setting_device_info_version_get(ccapi_rci_info_t * const info, uint32_t * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = 0x20101010;
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_info_error_id_t rci_setting_device_info_product_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "String";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_info_error_id_t rci_setting_device_info_product_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_info_error_id_t rci_setting_device_info_model_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "String";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_info_error_id_t rci_setting_device_info_model_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_info_error_id_t rci_setting_device_info_company_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "String";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_info_error_id_t rci_setting_device_info_company_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_info_error_id_t rci_setting_device_info_desc_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "String";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_device_info_error_id_t rci_setting_device_info_desc_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_system_error_id_t rci_setting_system_start(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_system_error_id_t rci_setting_system_end(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_system_error_id_t rci_setting_system_description_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "String";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_system_error_id_t rci_setting_system_description_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_system_error_id_t rci_setting_system_contact_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "String";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_system_error_id_t rci_setting_system_contact_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_system_error_id_t rci_setting_system_location_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "String";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_system_error_id_t rci_setting_system_location_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_devicesecurity_error_id_t rci_setting_devicesecurity_start(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_devicesecurity_error_id_t rci_setting_devicesecurity_end(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_devicesecurity_error_id_t rci_setting_devicesecurity_identityVerificationForm_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "simple";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_devicesecurity_error_id_t rci_setting_devicesecurity_identityVerificationForm_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_setting_devicesecurity_error_id_t rci_setting_devicesecurity_password_set(ccapi_rci_info_t * const info, char const * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_state_device_state_error_id_t rci_state_device_state_start(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_state_device_state_error_id_t rci_state_device_state_end(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_state_device_state_error_id_t rci_state_device_state_system_up_time_get(ccapi_rci_info_t * const info, uint32_t * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = 123;
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_state_device_state_error_id_t rci_state_device_state_signed_integer_get(ccapi_rci_info_t * const info, int32_t * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = -100;
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_state_device_state_error_id_t rci_state_device_state_signed_integer_set(ccapi_rci_info_t * const info, int32_t const *const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    UNUSED_PARAMETER(value);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_state_gps_stats_error_id_t rci_state_gps_stats_start(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_state_gps_stats_error_id_t rci_state_gps_stats_end(ccapi_rci_info_t * const info)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_state_gps_stats_error_id_t rci_state_gps_stats_latitude_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "String";
    return CCAPI_GLOBAL_ERROR_NONE;
}

ccapi_state_gps_stats_error_id_t rci_state_gps_stats_longitude_get(ccapi_rci_info_t * const info, char const * * const value)
{
    UNUSED_PARAMETER(info);
    printf("    Called '%s'\n", __FUNCTION__);
    *value = "String";
    return CCAPI_GLOBAL_ERROR_NONE;
}
